# configuration file for the test script (you can copy/modify to experiment with it)


# Basic parameters
n_in:         6 # number of dithers
n_out:        1 # number of output images
nps:          8 # PSF oversampling factor
s_in:         .11 # input pixel scale in arcsec
s_out:        .035 # output pixel scale in arcsec
n1:           512 # PSF postage stamp size
rngseed:      3000 # random number generator seed

# input and output postage stamp sizes
insize: 128 128
outsize: 128 128
lambda: 1.29 # wavelength [um]

# Optional rolls (in degrees for each exposure) and camera distortions
# (shear is g1,g2 for each exposure; magnify is for each exposure)
roll: 0 0 0 0 0 0
shear: 0 0 0 0 0 0 0 0 0 0 0 0
magnify: 0 0 0 0 0 0

# how much Gaussian smoothing (in input pixels) to put in the output image
extrasmooth: 0.63

# bad pixel fraction (this script randomly kills pixels)
badfrac: .025

# boundary extension in arcsec
extbdy:       1. 

# target image leakage (in RMS units). target sqrt{U/C} (1e-3 is a reasonable choice)
uctarget:     1e-3 
# penalty for having different dependences on different inputs
flat_penalty: 1e-8 

# output file prefix
OUT: /hpc/group/cosmology/masaya/imcom_phase1/fluffy-garbanzo/2022_07_28_roman_obs_grid/out/
